In [7]:
import pandas as pd

In [8]:
path = 'Dataset.xlsx'

In [9]:

def show_data(file_path):

    df = pd.read_excel(file_path)
    print(df)
    return df

show_data(path)

     Gender  Age              Diagnose  Hemoglobin  Hematokrit  Lekosit  \
0         L    1             DM TYPE 2        12.6        37.1     7130
1         P    1  DM TYPE 2 + Penyerta        11.3        33.6    13730
2         P    1  DM TYPE 2 + Penyerta        13.3        39.5     8330
3         P    1  DM TYPE 2 + Penyerta        14.2        41.6    15680
4         L    1             DM TYPE 2        12.1        36.2    20590
...     ...  ...                   ...         ...         ...      ...
1018      P   84             DM TYPE 2        14.4        42.5     7840
1019      P   84  DM TYPE 2 + Penyerta        11.2        33.3    24030
1020      L   84  DM TYPE 2 + Penyerta        12.4        37.2     5510
1021      P   86             DM TYPE 2        11.7        33.5     4710
1022      P   86  DM TYPE 2 + Penyerta         9.0        26.0     6660

      Eritrosit  Trombosit  HbA1c  RBG
0          4.09     241000   10.6  150
1          3.96     259000    5.0   33
2          4.47     340000    9.2  161
3          4.95     364000   10.8  425
4          5.33     333000   11.0  247
...         ...        ...    ...  ...
1018       4.99     331000    7.3  220
1019       4.17     586000    7.8  231
1020       4.00     234000    8.8  472
1021       3.46     170000    7.9  155
1022       2.88     457000   10.3  518

[1023 rows x 10 columns]

,Gender,Age,Diagnose,Hemoglobin,Hematokrit,Lekosit,Eritrosit,Trombosit,HbA1c,RBG
0,L,1,DM TYPE 2,12.6,37.1,7130,4.09,241000,10.6,150
1,P,1,DM TYPE 2 + Penyerta,11.3,33.6,13730,3.96,259000,5.0,33
2,P,1,DM TYPE 2 + Penyerta,13.3,39.5,8330,4.47,340000,9.2,161
3,P,1,DM TYPE 2 + Penyerta,14.2,41.6,15680,4.95,364000,10.8,425
4,L,1,DM TYPE 2,12.1,36.2,20590,5.33,333000,11.0,247
...,...,...,...,...,...,...,...,...,...,...
1018,P,84,DM TYPE 2,14.4,42.5,7840,4.99,331000,7.3,220
1019,P,84,DM TYPE 2 + Penyerta,11.2,33.3,24030,4.17,586000,7.8,231
1020,L,84,DM TYPE 2 + Penyerta,12.4,37.2,5510,4.00,234000,8.8,472
1021,P,86,DM TYPE 2,11.7,33.5,4710,3.46,170000,7.9,155
1022,P,86,DM TYPE 2 + Penyerta,9.0,26.0,6660,2.88,457000,10.3,518

In [10]:
def print_data():
    df = show_data(path)
    return df.to_excel('Dataset_Bersih.xlsx', index=False)